from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader

import os
from datetime import datetime


def create_invoice(
    company,
    customer,
    phone,
    email,
    products,
    gst,
    discount,
    payment_method="Cash",
    payment_status="Paid"
):

    if not os.path.exists("invoices"):
        os.makedirs("invoices")

    invoice_number = (
        "INV-" +
        datetime.now().strftime("%Y%m%d-%H%M%S")
    )

    pdf_path = os.path.join(
        "invoices",
        invoice_number + ".pdf"
    )

    pdf = canvas.Canvas(
        pdf_path,
        pagesize=A4
    )

    width, height = A4

    # =========================
    # HEADER
    # =========================

    pdf.setFillColor(
        colors.HexColor("#5b21b6")
    )

    pdf.roundRect(
        30,
        height - 125,
        width - 60,
        95,
        10,
        fill=1,
        stroke=0
    )

    # =========================
    # LOGO
    # =========================

    logo_path = "logo.png"

    if os.path.exists(logo_path):

        try:

            logo = ImageReader(
                logo_path
            )

            pdf.drawImage(
                logo,
                45,
                height - 112,
                width=90,
                height=70,
                preserveAspectRatio=True,
                mask="auto"
            )

        except Exception:
            pass

    # =========================
    # COMPANY NAME
    # =========================

    pdf.setFillColor(colors.white)

    pdf.setFont(
        "Helvetica-Bold",
        17
    )

    pdf.drawString(
        145,
        height - 55,
        "CHANDU TECHNOLOGIES"
    )

    pdf.setFont(
        "Helvetica",
        8
    )

    pdf.drawString(
        145,
        height - 72,
        "Innovate • Build • Grow"
    )

    # Email
    pdf.drawString(
        145,
        height - 88,
        email
    )

    # =========================
    # INVOICE DETAILS
    # =========================

    pdf.setFont(
        "Helvetica-Bold",
        18
    )

    pdf.drawRightString(
        width - 50,
        height - 52,
        "INVOICE"
    )

    pdf.setFont(
        "Helvetica",
        8
    )

    pdf.drawRightString(
        width - 50,
        height - 68,
        invoice_number
    )

    pdf.drawRightString(
        width - 50,
        height - 82,
        datetime.now().strftime("%d-%m-%Y")
    )

    # =========================
    # CUSTOMER
    # =========================

    y = height - 155

    pdf.setFillColor(
        colors.HexColor("#5b21b6")
    )

    pdf.setFont(
        "Helvetica-Bold",
        11
    )

    pdf.drawString(
        50,
        y,
        "BILL TO"
    )

    pdf.setFillColor(colors.black)

    pdf.setFont(
        "Helvetica-Bold",
        11
    )

    pdf.drawString(
        50,
        y - 20,
        customer
    )

    pdf.setFont(
        "Helvetica",
        9
    )

    pdf.drawString(
        50,
        y - 37,
        "Phone: " + phone
    )

    # =========================
    # COMPANY DETAILS
    # =========================

    pdf.setFont(
        "Helvetica-Bold",
        10
    )

    pdf.drawRightString(
        width - 50,
        y - 5,
        company
    )

    pdf.setFont(
        "Helvetica",
        8
    )

    pdf.drawRightString(
        width - 50,
        y - 20,
        "Invoice Generated by"
    )

    # =========================
    # PRODUCT TABLE
    # =========================

    table_top = y - 65

    left = 45
    right = width - 45

    pdf.setFillColor(
        colors.HexColor("#ede9fe")
    )

    pdf.roundRect(
        left,
        table_top - 28,
        right - left,
        28,
        5,
        fill=1,
        stroke=0
    )

    pdf.setFillColor(colors.black)

    pdf.setFont(
        "Helvetica-Bold",
        9
    )

    col_product = 60
    col_quantity = 300
    col_price = 370
    col_total = 470

    pdf.drawString(
        col_product,
        table_top - 18,
        "PRODUCT"
    )

    pdf.drawString(
        col_quantity,
        table_top - 18,
        "QTY"
    )

    pdf.drawString(
        col_price,
        table_top - 18,
        "PRICE"
    )

    pdf.drawString(
        col_total,
        table_top - 18,
        "TOTAL"
    )

    # =========================
    # PRODUCTS
    # =========================

    current_y = table_top - 50

    subtotal = 0

    pdf.setFont(
        "Helvetica",
        9
    )

    for item in products:

        product = item["product"]
        quantity = item["quantity"]
        price = item["price"]

        item_total = quantity * price

        subtotal += item_total

        pdf.drawString(
            col_product,
            current_y,
            product
        )

        pdf.drawString(
            col_quantity,
            current_y,
            str(quantity)
        )

        pdf.drawString(
            col_price,
            current_y,
            f"Rs. {price:.2f}"
        )

        pdf.drawString(
            col_total,
            current_y,
            f"Rs. {item_total:.2f}"
        )

        pdf.setStrokeColor(
            colors.HexColor("#dddddd")
        )

        pdf.line(
            left,
            current_y - 8,
            right,
            current_y - 8
        )

        current_y -= 28

    # =========================
    # CALCULATIONS
    # =========================

    discount_amount = (
        subtotal * discount / 100
    )

    amount_after_discount = (
        subtotal - discount_amount
    )

    gst_amount = (
        amount_after_discount * gst / 100
    )

    grand_total = (
        amount_after_discount + gst_amount
    )

    # =========================
    # SUMMARY
    # =========================

    summary_y = current_y - 25

    pdf.setFillColor(
        colors.HexColor("#f5f3ff")
    )

    pdf.roundRect(
        320,
        summary_y - 90,
        220,
        105,
        8,
        fill=1,
        stroke=0
    )

    pdf.setFillColor(colors.black)

    pdf.setFont(
        "Helvetica",
        9
    )

    pdf.drawString(
        335,
        summary_y - 5,
        "Subtotal"
    )

    pdf.drawRightString(
        520,
        summary_y - 5,
        f"Rs. {subtotal:.2f}"
    )

    pdf.drawString(
        335,
        summary_y - 25,
        f"Discount ({discount:.1f}%)"
    )

    pdf.drawRightString(
        520,
        summary_y - 25,
        f"- Rs. {discount_amount:.2f}"
    )

    pdf.drawString(
        335,
        summary_y - 45,
        f"GST ({gst:.1f}%)"
    )

    pdf.drawRightString(
        520,
        summary_y - 45,
        f"Rs. {gst_amount:.2f}"
    )

    # =========================
    # GRAND TOTAL
    # =========================

    pdf.setFillColor(
        colors.HexColor("#5b21b6")
    )

    pdf.roundRect(
        330,
        summary_y - 82,
        190,
        28,
        5,
        fill=1,
        stroke=0
    )

    pdf.setFillColor(colors.white)

    pdf.setFont(
        "Helvetica-Bold",
        10
    )

    pdf.drawString(
        342,
        summary_y - 73,
        "GRAND TOTAL"
    )

    pdf.drawRightString(
        510,
        summary_y - 73,
        f"Rs. {grand_total:.2f}"
    )

    # =========================
    # PAYMENT DETAILS
    # =========================

    payment_y = summary_y - 120

    pdf.setFillColor(
        colors.HexColor("#5b21b6")
    )

    pdf.setFont(
        "Helvetica-Bold",
        10
    )

    pdf.drawString(
        50,
        payment_y,
        "PAYMENT DETAILS"
    )

    pdf.setFillColor(colors.black)

    pdf.setFont(
        "Helvetica",
        9
    )

    pdf.drawString(
        50,
        payment_y - 18,
        "Payment Method:"
    )

    pdf.setFont(
        "Helvetica-Bold",
        9
    )

    pdf.drawString(
        145,
        payment_y - 18,
        payment_method
    )

    pdf.setFont(
        "Helvetica",
        9
    )

    pdf.drawString(
        50,
        payment_y - 36,
        "Payment Status:"
    )

    pdf.setFont(
        "Helvetica-Bold",
        9
    )

    pdf.drawString(
        145,
        payment_y - 36,
        payment_status
    )

    # =========================
    # FOOTER
    # =========================

    pdf.setStrokeColor(
        colors.HexColor("#d8b4fe")
    )

    pdf.line(
        50,
        75,
        width - 50,
        75
    )

    pdf.setFillColor(
        colors.HexColor("#666666")
    )

    pdf.setFont(
        "Helvetica-Bold",
        9
    )

    pdf.drawCentredString(
        width / 2,
        58,
        "Thank you for your business!"
    )

    pdf.setFont(
        "Helvetica",
        8
    )

    pdf.drawCentredString(
        width / 2,
        43,
        "CHANDU TECHNOLOGIES • Smart Invoice Generator"
    )

    pdf.save()

    return pdf_path